version: "3.8"

services:
  n8n:
    image: n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=changeme123
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - NODE_ENV=production
      - GENERIC_TIMEZONE=Asia/Tehran
    volumes:
      - ./n8n-data:/home/node/.n8n
    networks:
      - n8nnet

  bot:
    build: ./linkedin-bot
    restart: unless-stopped
    volumes:
      - ./linkedin-bot:/usr/src/app
      - ./puppeteer-profile:/root/.puppeteer-profile
    working_dir: /usr/src/app
    command: sleep infinity
    networks:
      - n8nnet

networks:
  n8nnet:
    driver: bridge